BibleVerseApp/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace BibleVerseApp.Controllers
{
    //Controls home page links
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult About()
        {
            ViewBag.Message = "CST-247 Benchmark Assignment";

            return View();
        }
        
        public ActionResult AddVerse()
        {
            ViewBag.Message = "Fill out the form to add a new Bible Verse";

            return View();
        }

        public ActionResult Search()
        {
            ViewBag.Message = "Fill at least one field to search your saved Bible verses";

            return View();
        }
    }
}

BibleVerseApp/Controllers/SearchController.cs
using BibleVerseApp.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace BibleVerseApp.Controllers
{
    //Controls the search funtion on the search page
    public class SearchController : Controller
    {
        private VersesDB versesDB = new VersesDB();        
        private VerseList verseList = new VerseList();
        
        // GET: Search
        public ActionResult Index()
        {
            return View();
        }

        //takes in the search criteria from the search form, and returns matches
        [HttpPost]
        public ActionResult Search([Bind(Include = "Testament,Book,Chapter,Number,Text")] Models.SearchModel verse)
        {
            List<Table> tables = versesDB.Tables.ToList();
            List<VerseModel> temp = new List<VerseModel>();

            foreach (Table t in tables)
            {
                verseList.AddVerse(t.toVerse());
            }

            //if statements check if the fields were empty or not, and if not narrows the list down to the matches
            if (verse.Testament != null)
            {
                var testtest = from VerseModel in verseList.GetAllVerses()
                               where VerseModel.Testament.ToLower().Contains(verse.Testament.ToLower())
                               select VerseModel;

                temp.Clear();
                foreach (var v in testtest)
                {
                    temp.Add(v);
                }

                verseList.ClearList();
                foreach (var v in temp)
                {
                    verseList.AddVerse(v);
                }
            }
            if (verse.Book != null)
            {
                var testtest = from VerseModel in verseList.GetAllVerses()
                               where VerseModel.Book.ToLower().Contains(verse.Book.ToLower())
                               select VerseModel;

                temp.Clear();
                foreach (var v in testtest)
                {
                    temp.Add(v);
                }

                verseList.ClearList();
                foreach (var v in temp)
                {
                    verseList.AddVerse(v);
                }
            }
            if (verse.Chapter > 0)
            {
                var testtest = from VerseModel in verseList.GetAllVerses()
                               where VerseModel.Chapter.Equals(verse.Chapter)
                               select VerseModel;

                temp.Clear();
                foreach (var v in testtest)
                {
                    temp.Add(v);
                }

                verseList.ClearList();
                foreach (var v in temp)
                {
                    verseList.AddVerse(v);
                }
            }
            if (verse.Number > 0)
            {
                var testtest = from VerseModel in verseList.GetAllVerses()
                               where VerseModel.Number.Equals(verse.Number)
                               select VerseModel;

                temp.Clear();
                foreach (var v in testtest)
                {
                    temp.Add(v);
                }

                verseList.ClearList();
                foreach (var v in temp)
                {
                    verseList.AddVerse(v);
                }
            }
            if (verse.Text != null)
            {
                var testtest = from VerseModel in verseList.GetAllVerses()
                               where VerseModel.Text.ToLower().Contains(verse.Text.ToLower())
                               select VerseModel;

                temp.Clear();
                foreach (var v in testtest)
                {
                    temp.Add(v);
                }

                verseList.ClearList();
                foreach (var v in temp)
                {
                    verseList.AddVerse(v);
                }
            }

            //If the list ended up empty at the end, a "Not Found" page is displayed
            if (verseList.GetAllVerses().Count <= 0)
            {
                return View("NotFound");
            }
            //Sends the search results to a ResultsModel and shows the Results view with the newly created model
            else
            {
                //TODO make "Results"
                ResultsModel results = new ResultsModel(verseList.GetAllVerses());
                return View("Results", results);
            }
        }
    }
}

BibleVerseApp/Controllers/VersesController.cs
using BibleVerseApp.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace BibleVerseApp.Controllers
{
    //Controller for creating verses and adding them to the database
    public class VersesController : Controller
    {             
        private VersesDB versesDB1 = new VersesDB();

        // GET: Verses
        public ActionResult Index()
        {
            return View();
        }
        
        // POST: Verses/Create
        [HttpPost]
        public ActionResult Create([Bind(Include ="Testament,Book,Chapter,Number,Text")] Models.Table verse)
        {
            try
            {                
                versesDB1.Tables.Add(verse);
                versesDB1.SaveChanges();
                
                return View("Success");
            }
            catch
            {
                return View("Failure");
            }
        }
    }
}

BibleVerseApp/Views/Home/About.cshtml
@{
    ViewBag.Title = "About";
}
<h2>@ViewBag.Title</h2>
<h3>@ViewBag.Message</h3>

<p>This program was made to satisfy the requirements of the Benchmark Assignment for CST-247.</p>

BibleVerseApp/Views/Home/AddVerse.cshtml
@model BibleVerseApp.Models.VerseModel

@{
    ViewBag.Title = "Add Verse";
}

<!DOCTYPE html>

<body>
    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/jqueryval")
    
    
    @using (Html.BeginForm("Create", "Verses", FormMethod.Post)) 
    {
        @Html.AntiForgeryToken()
        
        <div class="form-horizontal">
            <h4>Add a Bible Verse</h4>
            <hr />
            @Html.ValidationSummary(true, "", new { @class = "text-danger" })
            <div class="form-group">
                @Html.LabelFor(model => model.Testament, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.Testament, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Testament, "", new { @class = "text-danger" })
                </div>
            </div>
    
            <div class="form-group">
                @Html.LabelFor(model => model.Book, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.Book, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Book, "", new { @class = "text-danger" })
                </div>
            </div>
    
            <div class="form-group">
                @Html.LabelFor(model => model.Chapter, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.Chapter, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Chapter, "", new { @class = "text-danger" })
                </div>
            </div>
    
            <div class="form-group">
                @Html.LabelFor(model => model.Number, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.Number, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Number, "", new { @class = "text-danger" })
                </div>
            </div>
    
            <div class="form-group">
                @Html.LabelFor(model => model.Text, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.Text, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Text, "", new { @class = "text-danger" })
                </div>
            </div>
    
            <div class="form-group">
                <div class="col-md-offset-2 col-md-10">
                    <button type="submit" class="btn btn-success" value="Create">Create</button>
                </div>
            </div>
        </div>
    }
    
    <div>
        @Html.ActionLink("Back to List", "Index")
    </div>
</body>

BibleVerseApp/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Home Page";
}

<div class="jumbotron" style="background-image: url(../../Content/Bible.jpg); background-size: cover">
    <h1 style="color: whitesmoke">Bible Verses</h1>
    <p class="lead" style="color: whitesmoke">This web application is great for entering your favorite bible verses for later study and reflection.</p> 
    <p><a class="btn btn-default" href="~/Home/About">Learn more &raquo;</a></p>
</div>

<div class="row">
    <div class="col-md-6">
        <h2>Getting started</h2>
        <p>
            Visit this page to add a verse to your collection. Just enter the Testament, Book, Chapter, Verse Number, and the Verse itself to create a new entry that you can search for and visit later.
        </p>
        <p><a class="btn btn-default" href="~/Home/AddVerse">Add Verse &raquo;</a></p>
    </div>

    <div class="col-md-6">
        <h2>Find what you're looking for</h2>
        <p>Click here to search for a specific verse within your collection. Search with Chapter and Verse, or even part of the verse itself! Try it now!</p>
        <p><a class="btn btn-default" href="~/Home/Search">Search &raquo;</a></p>
    </div>    
</div>

BibleVerseApp/Views/Home/Search.cshtml
@model BibleVerseApp.Models.SearchModel

@{
    ViewBag.Title = "Search for a verse";
}

<!DOCTYPE html>

<body>
    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/jqueryval")
    
    
    @using (Html.BeginForm("Search", "Search", FormMethod.Post)) 
    {
        @Html.AntiForgeryToken()
        
        <div class="form-horizontal">
            <h4>Search for a Bible verse</h4>
            <hr />
            @Html.ValidationSummary(true, "", new { @class = "text-danger" })
            <div class="form-group">
                @Html.LabelFor(model => model.Testament, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.Testament, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Testament, "", new { @class = "text-danger" })
                </div>
            </div>
    
            <div class="form-group">
                @Html.LabelFor(model => model.Book, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.Book, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Book, "", new { @class = "text-danger" })
                </div>
            </div>
    
            <div class="form-group">
                @Html.LabelFor(model => model.Chapter, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.Chapter, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Chapter, "", new { @class = "text-danger" })
                </div>
            </div>
    
            <div class="form-group">
                @Html.LabelFor(model => model.Number, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.Number, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Number, "", new { @class = "text-danger" })
                </div>
            </div>
    
            <div class="form-group">
                @Html.LabelFor(model => model.Text, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.Text, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Text, "", new { @class = "text-danger" })
                </div>
            </div>
    
            <div class="form-group">
                <div class="col-md-offset-2 col-md-10">
                    <button type="submit" class="btn btn-success" value="Search">Search</button>
                </div>
            </div>
        </div>
    }
    
    <div>
        @Html.ActionLink("Back to List", "Index")
    </div>
</body>